"""Add push token to PhoneStatus

Revision ID: 0d0794146f24
Revises: 5da726f31c42
Create Date: 2025-03-26 15:39:30.671106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d0794146f24'
down_revision = '5da726f31c42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phone_status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expo_push_token', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phone_status', schema=None) as batch_op:
        batch_op.drop_column('expo_push_token')

    # ### end Alembic commands ###
