"""Fix user_id type in phone_status

Revision ID: 19af0d406d3e
Revises: f5d2e68ce2f5
Create Date: 2025-03-14 14:17:57.313464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19af0d406d3e'
down_revision = 'f5d2e68ce2f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('linked_device', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['device_name'])
        batch_op.create_unique_constraint(None, ['fcm_token'])

    with op.batch_alter_table('phone_status', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('user_location', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_location', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('timestamp')

    with op.batch_alter_table('phone_status', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('user_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    with op.batch_alter_table('linked_device', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
