"""Recreating missing phone_status table

Revision ID: 29fcc7e6f033
Revises: 
Create Date: 2025-03-16 21:30:25.090354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29fcc7e6f033'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alert_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.drop_column('location_name')

    with op.batch_alter_table('linked_device', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_column('location_name')

    with op.batch_alter_table('phone_status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint(None, ['user_id'])
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_column('location_name')

    with op.batch_alter_table('saved_location', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_column('location_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_location', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('name')
        batch_op.drop_column('user_id')
        batch_op.drop_column('id')

    with op.batch_alter_table('phone_status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_name', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('linked_device', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')
        batch_op.drop_column('id')

    with op.batch_alter_table('alert_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_column('user_id')
        batch_op.drop_column('id')

    # ### end Alembic commands ###
