"""Added location_type to UserLocation

Revision ID: 2f6921026a30
Revises: 19af0d406d3e
Create Date: 2025-03-14 18:16:26.367763

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2f6921026a30'
down_revision = '19af0d406d3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phone_status', schema=None) as batch_op:
        batch_op.drop_index('phone_status_user_id_idx')
        batch_op.create_unique_constraint(None, ['user_id'])

    with op.batch_alter_table('user_location', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_type', sa.String(length=10), nullable=True))
        batch_op.drop_constraint('user_location_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_location', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('user_location_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.drop_column('location_type')

    with op.batch_alter_table('phone_status', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('phone_status_user_id_idx', ['user_id'], unique=True)

    # ### end Alembic commands ###
