"""Initial migration

Revision ID: 90e6a90bf9d6
Revises: 
Create Date: 2025-03-16 16:40:36.449693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90e6a90bf9d6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_history',
    sa.Column('location_name', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('location_type', sa.String(length=20), nullable=False),
    sa.Column('ai_decision', sa.String(length=10), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('location_name')
    )
    op.create_table('linked_device',
    sa.Column('location_name', sa.String(length=100), nullable=False),
    sa.Column('device_name', sa.String(length=100), nullable=False),
    sa.Column('fcm_token', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('location_name'),
    sa.UniqueConstraint('device_name'),
    sa.UniqueConstraint('fcm_token')
    )
    op.create_table('phone_status',
    sa.Column('location_name', sa.String(length=100), nullable=False),
    sa.Column('last_latitude', sa.Float(), nullable=True),
    sa.Column('last_longitude', sa.Float(), nullable=True),
    sa.Column('tracking_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('location_name')
    )
    op.create_table('saved_location',
    sa.Column('location_name', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('location_name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('secondary_device_token', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('email')
    )
    op.create_table('user_location',
    sa.Column('location_name', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('location_type', sa.String(length=10), nullable=True),
    sa.Column('radius', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('location_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_location')
    op.drop_table('user')
    op.drop_table('saved_location')
    op.drop_table('phone_status')
    op.drop_table('linked_device')
    op.drop_table('alert_history')
    # ### end Alembic commands ###
