"""Add anomaly detection fields

Revision ID: 9ae1c552dff5
Revises: eb4deae74d4e
Create Date: 2025-03-26 07:56:15.668829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ae1c552dff5'
down_revision = 'eb4deae74d4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location_visit_log',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id', 'latitude', 'longitude')
    )
    op.drop_table('linked_device')
    with op.batch_alter_table('alert_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('was_anomaly', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('reason', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alert_history', schema=None) as batch_op:
        batch_op.drop_column('reason')
        batch_op.drop_column('was_anomaly')

    op.create_table('linked_device',
    sa.Column('device_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('fcm_token', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='linked_device_user_id_fkey'),
    sa.UniqueConstraint('device_name', name='linked_device_device_name_key'),
    sa.UniqueConstraint('fcm_token', name='linked_device_fcm_token_key')
    )
    op.drop_table('location_visit_log')
    # ### end Alembic commands ###
