"""Add risk_score to alert_history

Revision ID: bc6d73cc192c
Revises: 9ae1c552dff5
Create Date: 2025-03-26 14:28:34.326230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc6d73cc192c'
down_revision = '9ae1c552dff5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alert_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('risk_score', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alert_history', schema=None) as batch_op:
        batch_op.drop_column('risk_score')

    # ### end Alembic commands ###
