"""Recreate migrations

Revision ID: e5aaceaf48dc
Revises: 
Create Date: 2025-03-12 04:45:12.479119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5aaceaf48dc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('location')
    with op.batch_alter_table('phone_status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_location', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phone_status', schema=None) as batch_op:
        batch_op.drop_column('last_location')

    op.create_table('location',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('visit_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_frequent', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='location_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='location_pkey')
    )
    # ### end Alembic commands ###
