"""Added tracking_active flag

Revision ID: f5d2e68ce2f5
Revises: e5aaceaf48dc
Create Date: 2025-03-13 23:54:21.523983

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f5d2e68ce2f5'
down_revision = 'e5aaceaf48dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phone_status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('last_longitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tracking_active', sa.Boolean(), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.create_unique_constraint(None, ['user_id'])
        batch_op.drop_column('is_moving')
        batch_op.drop_column('last_location')
        batch_op.drop_column('last_motion_time')
        batch_op.drop_column('last_known_latitude')
        batch_op.drop_column('last_known_longitude')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phone_status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_known_longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('last_known_latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('last_motion_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('last_location', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_moving', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('user_id',
               existing_type=sa.String(length=100),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('tracking_active')
        batch_op.drop_column('last_longitude')
        batch_op.drop_column('last_latitude')

    # ### end Alembic commands ###
